### ISSUE TITLE
please add 2 columns in the output file cwl.metrics.date.tsv" and adjust results.tsv acoordingly

### ISSUE THREAD

**Issue by awollam** [mgi-qc/cwl_exome_wgs_metrics_parser#9]
I would like to request to bring "SAMPLE" AND "LIBRARY" COLUMNS from InsertSizeMetrics.txt file into the output "cwl.metrics.date.tsv"
in cwl.metrics.parser.py script
I will formally request this in github as well
currently SAMPLE" AND "LIBRARY" columns exist and but they are usually blank (we pull these two columns from HsMetrics.txt. but I would like to get "SAMPLE" AND "LIBRARY" COLUMNS from InsertSizeMetrics.txt as well.
This is because of somatic exome models we hvae been seeing lately. somatic models cannot parse out sample names, only the common names. so this sample name info need to come from InsertSizeMetrics.txt

**Comment by awollam** [comment]
edited:instead of what I indicated above (as we don't know how the file will look if libraries are different/multiple) the better route maybe as below:
please grab #SEQ_ID from "VerifyBamId.selfSM" and insert a column as SEQ_ID in output file. This should tell us the sample name

**Comment by LMT337** [comment]
@awollam, we have that information already as part of the results.  I believe you can use that, if it's not enough, re-open this and we'll grab it from InsertSizeMetrics.
